# Generated by Django 5.2.8 on 2025-11-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_created_at_tag_is_active_tag_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag', verbose_name='Теги'),
        ),
    ]
